// users.js
export const users = [
  {
    id: 1,
    img: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "Michael Johnson",
    username: "michael_j",
    score: 95,
    gender: "male",
    birthDate: "15-05-1990",
  },
  {
    id: 2,
    img: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Jessica Miller",
    username: "jessica_m",
    score: 93,
    gender: "female",
    birthDate: "28-12-1988",
  },
  {
    id: 8,
    img: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Sophia Johnson",
    username: "sophia_j",
    score: 84,
    gender: "female",
    birthDate: "02-08-1995",
  },
  {
    id: 9,
    img: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "Isaac Wilson",
    username: "isaac_w",
    score: 79,
    gender: "male",
    birthDate: "18-04-1993",
  },
  {
    id: 10,
    img: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Chloe Davis",
    username: "chloe_d",
    score: 78,
    gender: "female",
    birthDate: "05-09-1991",
  },
  {
    id: 3,
    img: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Christopher Davis",
    username: "chris_d",
    score: 92,
    gender: "male",
    birthDate: "20-06-1989",
  },
  {
    id: 4,
    img: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Emily White",
    username: "emily_white",
    score: 91,
    gender: "female",
    birthDate: "12-02-1994",
  },
  {
    id: 5,
    img: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "Matthew Taylor",
    username: "matthew_t",
    score: 88,
    gender: "male",
    birthDate: "08-11-1992",
  },
  {
    id: 6,
    img: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Olivia Brown",
    username: "olivia_b",
    score: 87,
    gender: "female",
    birthDate: "14-07-1996",
  },
  {
    id: 7,
    img: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Daniel Smith",
    username: "daniel_s",
    score: 85,
    gender: "male",
    birthDate: "25-03-1997",
  },
  // Add more friends as needed
];
