export const yoga =[
    {
        id: "beginner",
        name:"Bhujangasana (Cobra Pose)",
        need:"To strengthen the spine, improve posture, and relieve stress and fatigue.",
        suitable:"The one who have a sedentary lifestyle or work long hours sitting in front of a computer. ",
        benefits:"Bhujangasana helps to stimulate the abdominal organs, improve digestion, and alleviate constipation. It also helps to strengthen the spine, shoulders, and arms, and tone the buttocks. Additionally, it helps to relieve stress and fatigue, and improve posture ",
        procedure:["1.	Lie flat on your stomach keeping your legs straight, feet together, heels slightly touching each other and toes pointing",
        "2.	Rest the palm of your hands by the side of your chest, your arms must be close to your body with elbows pointing outward",
        "3.	Rest your forehead on the floor and relax your body",
        "4.	Inhale and raise your forehead, neck and then shoulders",
        "5.	Using your back muscles raise your chest, now use the strength of your arms to raise your trunk",
        "6.	Look upward breathing normally. This is the final position",
        "7.	In the final position, your navel should not raise more than 3cm; with your pubic bones touching the floor",
        "8.	Hold this position for 20-25 seconds",
        "9.	To come back to starting position first exhale and then slowly lower your navel, chest, shoulders, neck, and forehead. Relax and take deep breaths"],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://cdn.yogajournal.com/wp-content/uploads/2007/08/Cobra-Pose_Andrew-Clark.gif?width=730",
    },
    {
        id:"beginner",
        name:"Vrikshasana (Tree Pose)",
        need:"helps to strengthen the legs, ankles, and feet, and relieve sciatica ",
        suitable:"people who want to improve their balance and coordination",
        benefits:"Vrikshasana helps to improve balance and stability, and strengthen the thighs, calves, and spine. It also helps to stretch the hips, groins, and thighs, and relieve stress and anxiety .",
        procedure:["1.Stand with your feet together or hip-width apart",
        "2.Shift your weight onto your left foot",
        "3.Bend your right knee and place the sole of your right foot on your left inner thigh",
        "4.Press your right foot into your left thigh, while pressing your left thigh into your right foot",
        "5.Bring your hands together in front of your heart",
        ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://cdn.yogajournal.com/wp-content/uploads/2022/01/Tree-Pose_Alt-1_2400x1350_Andrew-Clark.jpeg",

    },
    {
        id:"beginner",
        name:"Utkatasana (Chair Pose)",
        need:"It also helps to strengthen the legs, ankles, and feet, and relieve sciatica",
        suitable:"people who want to improve their balance and coordination",
        benefits:"Utkatasana helps to improve balance and stability, and strengthen the thighs, calves, and spine. It also helps to stretch the hips, groins, and thighs, and relieve stress and anxiety ",
        procedure:["1.	Stand with your feet together or hip-width apart",
        "2.	Shift your weight onto your left foot",
        "3.	Bend your right knee and place the sole of your right foot on your left inner thigh",
        "4.	Press your right foot into your left thigh, while pressing your left thigh into your right foot",
        "5.	Bring your hands together in front of your heart",
        "6.	Hold for 30 seconds to 1 minute.",
        "7.	Repeat on the other side.",
        ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://cdn.yogajournal.com/wp-content/uploads/2021/11/Chair-Pose_Andrew-Clark_2400x1350.jpg",


    },
    {
        id:"beginner",
        name:": Trikonasana (Triangle Pose).",
        need:"To improve their balance and coordination",
        suitable:"people who are sports personalities and want to make thair legs and body strong ",
        benefits:"Trikonasana helps to improve balance and stability, and strengthen the thighs, calves, and spine. It also helps to stretch the hips, groins, and thighs, and relieve stress and anxiety ",
        procedure:["1.	Stand with your feet hip distance apart on your starting mat",
        "2.	Spread your feet. From here, step your feet out so there is about 3.5–4 feet of distance between them.",
        "3.	Turn your feet to different angles. In triangle pose, your feet need to be turned at different angles so you can maneuver your body correctly. Your right foot and left foot should be pointed in slightly different directions. Turn your right foot away from your body, so your toes are pointing outward. Keep turning your right foot until it’s at a 90-degree angle. Now, pivot your left foot back so your toes form a roughly 45-degree angle pointing toward your body.",
        "4.	Hold your arms parallel to the floor. Raise your arms outward on either side. Form a line with your arms, going from the fingertips on one arm to the fingertips on the other arm, that runs roughly parallel to the floor. Stretch your fingertips out to each side. Make sure your palms are facing the floor and your shoulder blades are pinned back to your spine.",
        "5.	Inhale and reach your body to the right as you exhale. As you exhale, stretch your right arm as far as it will go to the right. Stop when you’ve reached as far as you can and hold your torso in place. Rotate your arms so that your left arm reaches up and your right arm reaches down. Ideally, the line of your arms forms a roughly 90-degree angle with the floor.",
        "6.	Place your right hand on your right shin. Reach as far down as you can comfortably. Try to touch your right hand to your right shin, ankle, or the floor. Feel free to use a prop, like a block, here. Touch whatever place is comfortable for you and allows you to keep your balance.",
        "7.	Stretch as much as you can. While touching your shin, ankle, or the floor, stretch as much as you can.",
        ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://mindbodygreen-res.cloudinary.com/image/upload/c_fill,w_2000,h_1200,g_auto,fl_lossy,f_jpg/org/n9js8c5yfknfb32o9.png",
    },
    {
        id:"beginner",
        name:"Marjaryasana",
        need:"To warm up your back for further spinal stretches",
        suitable:"the people with back pain ",
        benefits:["increasing mobility,Stretches the back and neck,Increases circulation of spinal fluid"],
        procedure:["   1. Start on your hands and knees. The starting position for cat pose is also called tabletop pose Get on all fours with your wrists directly below your shoulders and your knees directly below your hips.",
         "2.Spread your fingers wide and cup your palms slightly. Your middle finger should be facing forward, the rest of your fingers splayed. Press all five fingertips into the mat.",
         "3. Connect with your breathing. Inhale deeply through the nose, filling your lungs. Pause, then exhale slowly and deeply out your mouth.",
         "4.On an exhale, round your spine up towards the ceiling, keeping your tailbone tucked under. Round your shoulders back so that your shoulder blades fall in line alongside your spine.",
         "5.Tuck your chin towards your chest. Lengthen your neck to complete cat pose, but don't try to force your chin to touch your chest.",
         "6.Hold the stretch for 5 to 10 breath cycles.",
        "7.If you're only doing cat pose and not moving into another pose immediately, first lower and flatten your spine to return to tabletop position. Then lower your hips on an exhale to sit back on your heels.",
        ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://ayushnext.ayush.gov.in/thumb/thumb_719X395_cat-cow-pose-page.jpg",
    },
    {
        id:"intermediat",
        name:"Half-Moon Pose (Ardha Chandrasana)",
        need:"to improve their strength, balance, and focus",
        suitable:"the person who want to fit and strong health and immunity",
        benefits:["Helps develop your strength, balance, and focus",
    "Engages your thighs, hips, ankles, and feet."],
        procedure:["1.The pose involves standing on one leg, while the other leg is lifted and the opposite hand touches the ground.",
         "2.In a flow sequence, you would go from Triangle to Half Moon to Downward Facing Dog"],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://www.theyogacollective.com/wp-content/uploads/2019/10/Half-Moon-Pose-for-Pose-Page-e1574902052788.jpeg",
    },
    {
        id:"intermediat",
        name:"Revolved Triangle Pose ",
        need:"to improve the body strenght blood flow and to make body flexible",
        suitable:"the person who has problems related minor back pain and also those who has BP problem",
        benefits:["1.Helps develop your strength, balance, and focus",
        "2.Engages your thighs, hips, ankles, and feet",
        "3.If you opt to stretch your arm upward or over your head, you’ll also engage your core, shoulder, and arm muscles",  "4.Improves balance and counteracts the effects of sitting",
        "5.Helps to minimize the risk of getting injuries",
        ],
        procedure:["1The pose involves standing on one leg, while the other leg is lifted and the opposite hand touches the ground.", 
              "2 In a flow sequence, you would go from Triangle to Revolved Triangle to Downward Facing Dog.",
        ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://cdn.yogajournal.com/wp-content/uploads/2021/10/Revolved-Triangle-Pose_Andrew-Clark.jpg",
    },
    {
        id:"intermediat",
        name:" Revolved Extended Side Angle Pose (Parivrtta Parsvakonasana)",
        need:"to improve muscles strenght,flexibility and focus",
        suitable:"the person with minor problems related to hips,angles,and feet",
        benefits:["1.Helps develop your strength, balance, and focus",
        "2.Engages your thighs, hips, ankles, and feet",
        "3.If you opt to stretch your arm upward or over your head, you’ll also engage your core, shoulder, and arm muscles",  "4.Improves balance and counteracts the effects of sitting",
        "5.Helps to minimize the risk of getting injuries",
    ],
        procedure:["1.The pose involves standing on one leg, while the other leg is lifted and the opposite hand touches the ground",
        "2. In a flow sequence, you would go from Triangle to Revolved Extended Side Angle to Downward Facing Dog"
        ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://www.yoganatomy.com/wp-content/uploads/2018/01/side-angle-yoga-anatomy.jpg",
    },
    {
        id:"intermediat",
        name:"Standing Hand-To-Big Toe Pose (Utthita Hasta Padangusthasana)",
        need:"to improve balance ,focus",
        suitable:"the people who has problems related to postural imbalanceand and shoulder/arm",
        benefits:["1.If you opt to stretch your arm upward or over your head, you’ll also engage your core, shoulder, and arm muscles¹.",
        "2.improves balance and counteracts the effects of sitting",
        "3 .Helps to minimize the risk of getting injuries",
       " 4 .Brings out postural imbalances",
    ],
        procedure:[" The pose involves standing on one leg, while the other leg is lifted and the opposite hand touches the ground.",
        " In a flow sequence, you would go from Triangle to Standing Hand-To-Big Toe Pose to Downward Facing Dog.",
],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://beyogi.com/wp-content/uploads/2015/03/Extended-Hand-to-Big-Toe-Pose-Utthita-Hasta-Padangustasana.png",
    },
    {
        id:"intermediat",
        name:"Eagle Pose (Garudasana)",
        need:"to imporve foucs stength and oxygen supply in body",
        suitable:"the person who is facing problems like small time concentration",
        benefits:["1.Strengthens ankles and increases flexibility in shoulder joints",
        "2.Improves concentration for meditative practices",
    ],
        procedure:"The pose involves standing on one leg, while the other leg is lifted and the opposite hand touches the ground, In a flow sequence, you would go from Triangle to Eagle Pose to Downward Facing Dog.",
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://artoflivingretreatcenter.org/wp-content/uploads/2020/10/eagle_sidexside.jpg",
    },
    {
        id:"expert",
        name:"The Firefly Pose ",
        need:"to improve flexibility and focus",
        suitable:"the person who is facing problems like stress,and blood flow",
        benefits:["1.Improves hip flexibility.",
        "2.Opens the chest ",
        "3.Helps you find new strength and perspective.",
        "4.Tones the belly",
        ],
        procedure:["1.Start in a Standing Forward Bend, with your toes pointing slightly out and your knees slightly bent.",
        "2.Thread your right hand through your legs to clasp your right calf, positioning your right shoulder behind your right knee. ",
         "3.Repeat this process on the left side.",
        "4.Place your hands flat on the mat behind your feet. Arrange your hands shoulder-distance apart, the tips of the middle fingers grazing your heels",
        "5.Bend your knees deeply, and grab hold of your calves to snuggle one shoulder, and then the other, behind your knees. Your shoulders will round forward, but keep pushing them back against the thighs.",
    ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://cdn.yogajournal.com/wp-content/uploads/2021/11/Titibasana-Firefly-Sequence-Featured-Renee-Choi-scaled.jpg",
    },
    {
        id:"expert",
        name:" The King Pigeon Pose is also known as Eka Pada Rajakapotasana",
        need:"to improve back related problems and for improper posture",
        suitable:"the people who is facing problems with improper posture and backpain",
        benefits:["1.Stretches the entire front of the body, the ankles, thighs and groins, abdomen and chest, and throat.",
         "2.stretches the deep hip flexors .",
        "3.Strengthens back muscles.",
        	"4.Improves posture",
        ],
        procedure:["1.Kneel upright, with your knees slightly narrower than hip width apart and your hips, shoulders, and head stacked directly above your knees.",
        "2.With your hands, press down against the back of your pelvis.",
       " 3.On an inhalation, tuck your chin toward your sternum and lean your head and shoulders back as far as you can without pushing your hips forward.",
       " 4.Firm your shoulder blades against your back and lift the top of your sternum.",
       " 5.When your chest is maximally lifted, gradually release your head back",
        "6.Before you arch all the way back and place your head and hands on the floor, bring your palms together in front of your sternum in Anjali Mudra.",
        "7.Then separate your hands and reach them overhead toward the floor behind you.",
        "8.Bring your hips forward enough to counterbalance the backward movement of the upper torso and head.",
    ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/sites/45434/images/d6da8-3a8-c8a2-8b26-f0d7850bbf2_A.jpg",
    },
    {
        id:"expert",
        name:"The Lord of the Dance Pose is also known as Natarajasana",
        need:"to improve concentration and balance as well as self-control",
        suitable:"to people with short-tempered behaveiour",
        benefits:"Increases the flexibility of the spine.	Stretches the hamstrings and the quadriceps.",
        procedure:["1.Begin standing in Mountain Pose.",
        "2.Keeping your right leg strong and balanced, lift up your left leg and with your left outreached hand grasp your left foot from the inside. Hold your left leg. Lift your right arm straight to the ceiling.",
         "3.Begin to lift your left leg behind you, pulling it ever so slightly with your left arm. As you do so, lift your chest, squaring your hips.",
         "4.Use the resistance of your leg pulling against your arms to establish a straight line along the legs. Hold this position for up to 30 seconds.",
         "5.To release, simply let go of your leg and release it back down to the mat to Mountain Pose. ",
        ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://www.everydayyoga.com/cdn/shop/articles/Yoga_Young-Woman-Doing-King-Dancer-Pose-Outside_01_300x350_b27b1569-6f54-4b6c-80d3-db950590c55c_grande.jpg?v=1558424651",
    },
    {
        id:"expert",
        name:"Name: The Lotus Pose is also known as Padmasana",
        need:"to imporve back muscles and respiration process",
        suitable:"people facing with back-bone problem and respiratory problems",
        benefits:["1.Increases knee and hip flexibility.",
        "2.Promotes better posture.",
        "3.Strengthens core and back muscles.",
        ],
        procedure:["1.Begin in a general seated position, legs straight out in front of you.",
        "2.Bend down and pull right leg up, curving at the hip joint, not at the knee.",
        "3.Rest your right foot in the crook of your left arm, the right knee in the crook of your right arm, and relax",
        "4.Start by sitting on your mat with both legs extended in front of you.",
        "5.Fold one leg and place the ankle on the opposite thigh, close to the hip joint.",
        "6.Once you’re comfortable with the first leg in position, fold the other leg in the same manner, placing its ankle on the opposite thigh.",
        "7.Both feet should be resting on the opposite thighs with the soles facing upwards. The tops of your feet should nestle into the creases of your hips.",
        "8.Your knees should ideally be touching the ground. If they don’t, don’t force them. Over time, with consistent practice and hip-opening exercises, they will lower naturally.",
        "9.Sit tall and make sure that your spine is long and straight. This can help you breathe properly and keep you alert during meditation. ",
    ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://images.ganeshaspeaks.com/yoga/lotus-position-padmasana.webp",
    },
    {
        id:"expert",
        name:"Name: The Peacock Pose is also known as Mayurasana",
        need:"to imporve digestion and controlled diabetes.",
        suitable:"the people who face problems of digestion and also diabetes",
        benefits:["1.Aids in health conditions like constipation, flatulence, and diabetes.",
        "2.Strengthens the core while stretching the palm side of the wrists.",
        "3.Releases tension in the body, elongates your limbs and challenges your balancing skills.",
    ],
        procedure:["1.Start in an upright seated position. Sit on your knees and heels in the Hero Pose (Virasana). Keeping some distance between your knees will open up your hips.",
        "2.Lean your shoulders forward and place your hands on the ground in front of you. As you lean forward, your elbows will bend slightly. Make sure your hands and elbows face inward towards your heart.",
        "3.As you press your palms into the floor, your torso will press against the back of your upper arms. Your head will come forward towards the mat.",
        "4.Unbend your knees and extend your legs behind you, toes facing the floor.",
    ],
        time:"minimum 60 sec (1 min)-maximum 300 sec (5 min)",
        img:"https://www.theyogacollective.com/wp-content/uploads/2020/04/Advanced-Arm-Balance-1-1200x800.jpeg",
    },
    

]